name: Test Commit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
      - name: Install dependencies
        run: |
          pnpm install
      - name: Lint
        run: pnpx eslint .
      - name: Unit tests
        run: pnpx jest --ci --coverage
      - name: Build
        run: pnpm build
      - name: Codecov
        run: npx codecov -f coverage/*.json
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
